export enum URLs {

    HOME_PAGE = 'https://www.automationexercise.com/',
    PRODUCTS_PAGE = 'https://www.automationexercise.com/products',
    SHOPPING_CART_PAGE = 'https://www.automationexercise.com/view_cart',
    LOGIN_PAGE = 'https://www.automationexercise.com/login',
    TEST_CASES_PAGE = 'https://www.automationexercise.com/test_cases',
    API_TESTING_PAGE = 'https://www.automationexercise.com/api_list',
    VIDEO_TUTORIALS_PAGE = 'https://consent.youtube.com/',
    CONTACT_US_PAGE = 'https://www.automationexercise.com/contact_us',
    DRESS_PAGE = 'https://www.automationexercise.com/category_products/1',
    TOPS_PAGE = 'https://www.automationexercise.com/category_products/2',
    SAREE_PAGE = 'https://www.automationexercise.com/category_products/7',
    TSHIRTS_PAGE = 'https://www.automationexercise.com/category_products/3',
    JEANS_PAGE = 'https://www.automationexercise.com/category_products/6',
    KIDS_DRESS_PAGE = 'https://www.automationexercise.com/category_products/4',
    TOPS_AND_SHIRTS_PAGE = 'https://www.automationexercise.com/category_products/5',
    POLO_PAGE = 'https://www.automationexercise.com/brand_products/Polo',
    H_And_M_PAGE = 'https://www.automationexercise.com/brand_products/H&M',
    MADAME_PAGE = 'https://www.automationexercise.com/brand_products/Madame',
    MAST_AND_HARBOUR_PAGE = 'https://www.automationexercise.com/brand_products/Mast%20&%20Harbour',
    BABYHUG_PAGE = 'https://www.automationexercise.com/brand_products/Babyhug',
    ALLEN_SOLLY_JUNIOR_PAGE = 'https://www.automationexercise.com/brand_products/Allen%20Solly%20Junior',
    KOOKIE_KIDS_PAGE = 'https://www.automationexercise.com/brand_products/Kookie%20Kids',
    BIBA_PAGE = 'https://www.automationexercise.com/brand_products/Biba',
    CHECKOUT_PAGE = 'https://www.automationexercise.com/checkout',
    PAYMENT_PAGE = 'https://www.automationexercise.com/payment'
}